name: Welcome New Contributors

on:
  pull_request:
    types: [opened]
    branches: [main]

permissions:
  issues: write
  pull-requests: write
  contents: read
  metadata: read

jobs:
  welcome:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get PR info
        id: pr-info
        run: |
          echo "username=${{ github.event.pull_request.user.login }}" >> $GITHUB_OUTPUT
          echo "pr_number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            const username = "${{ steps.pr-info.outputs.username }}";
            const prNumber = ${{ steps.pr-info.outputs.pr_number }};
            
            console.log(`PR #${prNumber} opened by: ${username}`);
            
            const message = `🎉 Thank you for contributing to CanConf, @${username}! 
            
            Your contribution helps make Canadian tech events more discoverable for everyone. 🇨🇦
            
            Once this PR is merged, you'll be automatically added to our contributors list on the website!
            
            ---
            *This comment was automatically generated by our contributor recognition system.*`;
            
            try {
              const result = await github.rest.issues.createComment({
                issue_number: prNumber,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: message
              });
              console.log('Welcome comment posted successfully!', result.data.html_url);
            } catch (error) {
              console.error('Failed to post comment:', error);
              console.error('Error details:', JSON.stringify(error.response?.data, null, 2));
              
              // Log the welcome message even if we can't post it
              console.log('\n=== WELCOME MESSAGE (could not post as comment) ===');
              console.log(message);
              console.log('=== END WELCOME MESSAGE ===\n');
              
              // Don't fail the workflow, just log the error
              console.log('Continuing workflow despite comment failure...');
            }
